/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : Status,
  'selectedService' : Service,
  'preferredDate' : string,
  'timestamp' : Time,
  'phoneNumber' : string,
}
export type Service = { 'eyeBrow' : null } |
  { 'pedicure' : null } |
  { 'hairSpa' : null } |
  { 'facials' : null } |
  { 'partyMakeup' : null } |
  { 'waxing' : null } |
  { 'manicure' : null } |
  { 'hairColor' : null } |
  { 'bridalMakeup' : null } |
  { 'hairCutting' : null };
export type Status = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface _SERVICE {
  'approveBooking' : ActorMethod<[bigint], undefined>,
  'bookAppointment' : ActorMethod<
    [
      {
        'customerName' : string,
        'selectedService' : Service,
        'preferredDate' : string,
        'phoneNumber' : string,
      },
    ],
    bigint
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBookingsByCustomerName' : ActorMethod<[string], Array<Booking>>,
  'rejectBooking' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];