/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Service = IDL.Variant({
  'eyeBrow' : IDL.Null,
  'pedicure' : IDL.Null,
  'hairSpa' : IDL.Null,
  'facials' : IDL.Null,
  'partyMakeup' : IDL.Null,
  'waxing' : IDL.Null,
  'manicure' : IDL.Null,
  'hairColor' : IDL.Null,
  'bridalMakeup' : IDL.Null,
  'hairCutting' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'selectedService' : Service,
  'preferredDate' : IDL.Text,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func([Booking], [IDL.Nat], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBookingsByCustomerName' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Service = IDL.Variant({
    'eyeBrow' : IDL.Null,
    'pedicure' : IDL.Null,
    'hairSpa' : IDL.Null,
    'facials' : IDL.Null,
    'partyMakeup' : IDL.Null,
    'waxing' : IDL.Null,
    'manicure' : IDL.Null,
    'hairColor' : IDL.Null,
    'bridalMakeup' : IDL.Null,
    'hairCutting' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'selectedService' : Service,
    'preferredDate' : IDL.Text,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func([Booking], [IDL.Nat], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBookingsByCustomerName' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };