/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Booking {
    id: bigint;
    customerName: string;
    status: Status;
    selectedService: Service;
    preferredDate: string;
    timestamp: Time;
    phoneNumber: string;
}
export type Time = bigint;
export enum Service {
    eyeBrow = "eyeBrow",
    pedicure = "pedicure",
    hairSpa = "hairSpa",
    facials = "facials",
    partyMakeup = "partyMakeup",
    waxing = "waxing",
    manicure = "manicure",
    hairColor = "hairColor",
    bridalMakeup = "bridalMakeup",
    hairCutting = "hairCutting"
}
export enum Status {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    approveBooking(id: bigint): Promise<void>;
    bookAppointment(input: {
        customerName: string;
        selectedService: Service;
        preferredDate: string;
        phoneNumber: string;
    }): Promise<bigint>;
    getAllBookings(): Promise<Array<Booking>>;
    getBookingsByCustomerName(customerName: string): Promise<Array<Booking>>;
    rejectBooking(id: bigint): Promise<void>;
}
import type { Booking as _Booking, Service as _Service, Status as _Status, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveBooking(arg0);
            return result;
        }
    }
    async bookAppointment(arg0: {
        customerName: string;
        selectedService: Service;
        preferredDate: string;
        phoneNumber: string;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(to_candid_record_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(to_candid_record_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByCustomerName(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByCustomerName(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByCustomerName(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBooking(arg0);
            return result;
        }
    }
}
function from_candid_Booking_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _Status;
    selectedService: _Service;
    preferredDate: string;
    timestamp: _Time;
    phoneNumber: string;
}): {
    id: bigint;
    customerName: string;
    status: Status;
    selectedService: Service;
    preferredDate: string;
    timestamp: Time;
    phoneNumber: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_Status_n7(_uploadFile, _downloadFile, value.status),
        selectedService: from_candid_Service_n9(_uploadFile, _downloadFile, value.selectedService),
        preferredDate: value.preferredDate,
        timestamp: value.timestamp,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eyeBrow: null;
} | {
    pedicure: null;
} | {
    hairSpa: null;
} | {
    facials: null;
} | {
    partyMakeup: null;
} | {
    waxing: null;
} | {
    manicure: null;
} | {
    hairColor: null;
} | {
    bridalMakeup: null;
} | {
    hairCutting: null;
}): Service {
    return "eyeBrow" in value ? Service.eyeBrow : "pedicure" in value ? Service.pedicure : "hairSpa" in value ? Service.hairSpa : "facials" in value ? Service.facials : "partyMakeup" in value ? Service.partyMakeup : "waxing" in value ? Service.waxing : "manicure" in value ? Service.manicure : "hairColor" in value ? Service.hairColor : "bridalMakeup" in value ? Service.bridalMakeup : "hairCutting" in value ? Service.hairCutting : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Status {
    return "pending" in value ? Status.pending : "approved" in value ? Status.approved : "rejected" in value ? Status.rejected : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n5(_uploadFile, _downloadFile, x));
}
function to_candid_Service_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    selectedService: Service;
    preferredDate: string;
    phoneNumber: string;
}): {
    customerName: string;
    selectedService: _Service;
    preferredDate: string;
    phoneNumber: string;
} {
    return {
        customerName: value.customerName,
        selectedService: to_candid_Service_n2(_uploadFile, _downloadFile, value.selectedService),
        preferredDate: value.preferredDate,
        phoneNumber: value.phoneNumber
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): {
    eyeBrow: null;
} | {
    pedicure: null;
} | {
    hairSpa: null;
} | {
    facials: null;
} | {
    partyMakeup: null;
} | {
    waxing: null;
} | {
    manicure: null;
} | {
    hairColor: null;
} | {
    bridalMakeup: null;
} | {
    hairCutting: null;
} {
    return value == Service.eyeBrow ? {
        eyeBrow: null
    } : value == Service.pedicure ? {
        pedicure: null
    } : value == Service.hairSpa ? {
        hairSpa: null
    } : value == Service.facials ? {
        facials: null
    } : value == Service.partyMakeup ? {
        partyMakeup: null
    } : value == Service.waxing ? {
        waxing: null
    } : value == Service.manicure ? {
        manicure: null
    } : value == Service.hairColor ? {
        hairColor: null
    } : value == Service.bridalMakeup ? {
        bridalMakeup: null
    } : value == Service.hairCutting ? {
        hairCutting: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
